### ISSUE TITLE
File Parameter can't be referenced by Uno-Choice, and interferes with other parameters

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#23]
It appears that a file parameter can't be referenced by an Uno-Choice control. File parameters are used to upload files to the server. Being able to reference the 'File Location' parameter in a Uno-Choice control should be supported.

![untitled_clipping_080414_123738_pm](https://cloud.githubusercontent.com/assets/3408226/3800190/a7864630-1bf5-11e4-85dd-50c1b067ac25.jpg)

In addition, when a file parameter is added to the list of uno-choice referenced parameters the entire parameter binding seems to be in error.

The following Parameters list works ok
![untitled_clipping_080414_123942_pm](https://cloud.githubusercontent.com/assets/3408226/3800215/f154438e-1bf5-11e4-9e68-6b5efb426a7f.jpg)

Adding the File Parameter breaks all other parameters as well!
![untitled_clipping_080414_124249_pm](https://cloud.githubusercontent.com/assets/3408226/3800257/606c875e-1bf6-11e4-9e8c-f18daf1acf82.jpg)

and it results in the following UI
![untitled_clipping_080414_124419_pm](https://cloud.githubusercontent.com/assets/3408226/3800278/9648388c-1bf6-11e4-95ac-ada839dbfb7e.jpg)

**Comment by imoutsatsos** [comment]
The value of a file parameter is not returned using UC v0.23

See: http://162.243.246.75:8080/job/issue-23/build

![image](https://cloud.githubusercontent.com/assets/3408226/6304992/26a7a0b0-b8f6-11e4-9acc-9f7b2009c6ee.png)

**Comment by kinow** [comment]
Had a look at the commit that fixed the issue, seems like it's not so hard to fix (and write a test for it). Will try to fix it till this weekend and deploy a new version in our testing instance.

**Comment by kinow** [comment]
Just deployed a new version. Can you take a look if that's fixed, please Ioannis?! :-)

The issue was caused during the refactoring of the code. Quite simple to fix.

**Comment by imoutsatsos** [comment]
This looks good! closing and hope it will never come back again with the new tests in place! Thanks Bruno!

**Comment by kinow** [comment]
>hope it will never come back again with the new tests in place! 

Err, forgot to mention. I couldn't write a test for it. Actually, there is already a test in place, but it is not working due to JavaScript security. IIUC, there is no way to change file upload with JavaScript, as that could take to security problems in browsers.

**Comment by imoutsatsos** [comment]
...in that case I trust in your programming magic! ;-)
