### ISSUE TITLE
Maintain Uno-Choice selections between filter applications

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#36]
Any selections made using the current uno-choice control are lost when the options list is updated after you apply a filter. It would be useful to **maintain the existing selections between filtering operations** of the same list. 

This becomes even more important when the options list is long and the filter (a really useful feature of the current implementation) allows you to select successive related options

**Comment by kinow** [comment]
Hmmm, this issue will probably stay behind after the 1.0 release. We can ship it into a version later 1.0.

**Comment by kinow** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-28734
