### ISSUE TITLE
Access to build environment variables in "Uno Choice Cascade Dynamic Choice Parameter"?

### ISSUE THREAD

**Issue by tknerr** [biouno/uno-choice-plugin#44]
Hi everybody,

is it possible to access build environment variables within the "Choices Script" of an "Uno Choice Cascade Dynamic Choice Parameter"?

Specifically, I wanted to do something like this:
```groovy
def fooValue = build.buildVariableResolver.resolve('foo')
``` 

However, I have no clue on how to get hold of the `build` object representing the currently executing build.

Is it possible at all?

**Comment by kinow** [comment]
Hello @tknerr 

Sorry for the delay. Here's how to access environment variables:

```
def env = System.getenv()
def pass = env['MY_APP_PASS']
// ... rest of the code
return [] // return something
```

Just tested it with the latest version, and seems to work. Can you give it a try, please?

**Comment by devgeek578** [comment]
Hi @kinow 

I'm trying to access the environment variables but the method you described doesn't seem to be working:

dev testVar = System.getenv()
return testVar['WORKSPACE']

**Comment by kinow** [comment]
Hi @devgeek578, can you check please if other variables such as PATH, HOME, JENKINS_HOME, etc can be accessed with this approach? I don't recall right now, but I believe the workspace is set for the build, but not for the parameter screen.

**Comment by devgeek578** [comment]
Thanks for the reply @kinow !

I'm not able to access any of those either:

def testVar = System.getenv()
return testVar[JENKINS_HOME]

From what I'm reading it sounds like you're right with the environment variables not being available until the build starts. I understand variables not being available because the values are dependent on the build (ie, BUILD_NUMBER, BUILD_URL, BUILD_ID, etc.), but static variables like WORKSPACE and JOB_NAME should be available at any point.

**Comment by kinow** [comment]
No worries. You are probably right, I don't have my workspace open at the moment to try, but considering the Workspace variable will be available and set, there are two strange things that I would investigate in this issue:
a) Why the other variables are not set (PATH was supposed to work I think). I'd take a look if there is another way to access env vars in Groovy or some peculiarity with my OS.
b) Would try to import https://github.com/jenkinsci/jenkins/blob/7a64e030a38561c98954c4c51c4438c97469dfd6/core/src/main/java/hudson/EnvVars.java#L382 and use one of its methods to resolve the variable. Maybe that way we can access the WORKSPACE var?
Will be able to give it a try either tonight or Sunday (GMT-3), but let me know if you made any progress on this.

Hope that helps,Bruno

**Comment by devgeek578** [comment]
Hi @kinow 

I was able to come up with a workaround using the method discussed here: https://github.com/biouno/uno-choice-plugin/issues/16#issuecomment-69653280

One last issue that I'm trying to figure out is how to access global properties inside this parameter value? I'm going to create a list of key value pairs as Global Properties to hold paths to be shared across several jobs.

**Comment by kinow** [comment]
Hmmm, I'd have to set up a sample jenkins to try that. I never really used global properties in parameters. @imoutsatsos have you by any chance?

**Comment by kinow** [comment]
Closing the issue, we can continue the discussion in the mailing list, or if there's a bug or enhancement, we can move that to https://issues.jenkins-ci.org (component = active-choices-plugin). Thanks!
