### ISSUE TITLE
New parameter type

### ISSUE THREAD

**Issue by gilShin** [biouno/uno-choice-plugin#47]
I would like to have a new parameter type that'll be a Boolean.
This new type will be a multi check box selection that if one selects a check boxes, the value of that parameter of that check box would be true and if it will be left unticked, its value would be false.

**Comment by kinow** [comment]
ping @gilShin ? We're preparing to release 1.0 to all Jenkins users, and probably we'll move some issues to Jenkins JIRA or will close them before releasing.

**Comment by kinow** [comment]
We need a better use case and example in order to work on this new parameter type. Please file an issue on https://issues.jenkins-ci.org, with component name active-choices-plugin if you can provide this information :-) Thanks!
