### ISSUE TITLE
Fatal Errors when Uno-Choice returns a null value

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#68]
Using v0.22 snapshot. This is related to two previously reported issues #30 and #59 
![image](https://cloud.githubusercontent.com/assets/3408226/5474522/176905ec-85e0-11e4-9e89-c68865ff5c00.png)

![image](https://cloud.githubusercontent.com/assets/3408226/5474530/249e6a4a-85e0-11e4-8204-5ef8ce6b9b30.png)

You can reproduce it on the test server at:
http://162.243.246.75:8080/job/cascade-exampleStateCities

Note that you actually need a build step (any!) for it to fail. In most of our tests we don't actually have a build step so we don't catch this. I have now added a trivial groovy step.

It works fine when a Cities option is selected, but there are legitimate reason where you may not want to select an option.

At any rate it looks like we might have to extend the strategy used for the resolution of #30 which was to pass in a default parameter if the user did not select any values from the control

**Comment by kinow** [comment]
Not as tricky as I thought it earlier. In summary, added a verification to change the value to an empty String if the value returned by the parameter was null. I believe it now mimics the behaviour in Jenkins.

**Comment by kinow** [comment]
Deployed to our testing server, seems to be working. Please give it a try @imoutsatsos :D

**Comment by kinow** [comment]
Seems to be working now. We have released 1.0, so this issue can be re-opened in https://issues.jenkins-ci.org, component name active-choices-plugin if it still persists
