### ISSUE TITLE
Uno-choice Scriptler configuration displays static cached parameter values

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#69]
Sorry that Scriptler script testing is coming so late in the process!

Our famous example of Brazilian State-Cities cascade has now been implemented with a Scriptler script. Re-opening the configuration I see a new Scriptler parameter (**States** ) that **I did not add** . 
![untitled_clipping_121714_032403_pm](https://cloud.githubusercontent.com/assets/3408226/5478250/bf9a50d4-8600-11e4-9123-a4a3be98f426.jpg)

Q: I know that the referenced parameters are passed into the script binding. Is this what you are trying to display here? If that's the case, the static value displayed for the States parameter is confusing

I vote not to show this parameter as it is more likely to confuse. 

Also, I'm re-opening #16 as it does not appear to work in v0.22. It seems that the Scriptler script requires a hard coded reference into the job parameter. The two should be decoupled using the Scriptler parameters.

**Comment by kinow** [comment]
Hi @imoutsatsos, I'm going have to ask you to check if this issue has been fixed. I couldn't test it before fixing two other issues today. But think it is not happening anymore.

The best explanation I have, is that before we were "merging" the UI parameters, with the Scriptler job configuration parameters. Causing the "cached" value (actually the value selected in the UI, that got merged with the scriptler params) to appear in the job configuration screen.

I believe we can close it as won't fix, but please give it a few tries and let me know if that still occurs. Going to bed now, will have another development cycle this weekend or during the next weekend. Cheers!

**Comment by imoutsatsos** [comment]
Thanks @kinow ! I will retest all the issues you fixed this weekend this coming week. Looks like things are really ready for releasing the Jenkins hosted uno-choice v1.0! Exciting!!

**Comment by kinow** [comment]
Thank you too for your patience and thorough testing @imoutsatsos ! 

And indeed, 2015 seems to be a promising year for Uno-Choice plug-in. Once tis released I'll bother you other ideas :)

**Comment by imoutsatsos** [comment]
Looks good on our Jenkins Test server @kinow ! I will further test with some projects at work today (where scriptlets are heavily used) and I will close. All of my project have now been transferred to the new code base and I'm quite pleased! Uno-choice is quite solid! Thanks!!

**Comment by kinow** [comment]
Yay, thanks for (again) thoroughly testing the changes. Some users reported the plug-in being slow in some cases. I'm waiting for their feedback, but I think it should not be a blocker for a 1.0 (after all, 1.1 is just a matter of few shell commands to release).

**Comment by imoutsatsos** [comment]
I think the old code base was slow performing. I had Jenkins build forms with 6-10 Uno-choice controls and you did have to wait for a few seconds to load and update. However, I'm finding the new code base much improved. I will give you some additional feedback once my UC v0.23 projects have been deployed for general use. Doing a 'production' roll out today!

**Comment by kinow** [comment]
Good luck Ioannis! Drop me a message if you need anything :D

**Comment by kinow** [comment]
Sees to be working now in 1.0. Please feel free to re-open an issue in https://issues.jenkins-ci.org/ with component name active-choices-plugin in case the issue persists. Thanks!
