### ISSUE TITLE
Filter not active when Uno-Choice options are refreshed

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#71]
In the current implementation of UC cascade dynamic parameter the filter is no longer in effect once the UC gets updated. The current filter should also take effect once the options list is updated from a parameter change trigger.

I will write a test job to go along with it...

**Comment by kinow** [comment]
Thanks @imoutsatsos ! I'll take a look at the job once you've created it and will try to fix it during this weekend :-)

**Comment by imoutsatsos** [comment]
Hi @kinow!
I have now added an example that you can check with the new code updates.
http://162.243.246.75:8080/job/issue-71

Have a good weekend!

**Comment by kinow** [comment]
Will open the Eclipse workspace in a few minutes. 

Thanks Ioannis! Have a great weekend too! I'll have fun with Uno Choice and with the PBS Plug-in :D

**Comment by kinow** [comment]
Hello again @imoutsatsos!

I think that after you selected **Female**, the filter should be cleared. We can trick the browser by sending a key up event and pretend that the HTML element is being filtered. But I think it would be easier to simply clear the filter text field. 

What do you think?

**Comment by kinow** [comment]
Perhaps in the future we can evolve to better filtering. Where we can add several filters like in some web stores. Then you could pin filters to your job configuration, and they would get used across your selections. 

At the moment we have one of the simplest filters I think.

**Comment by imoutsatsos** [comment]
Hi @kinow and thanks for looking into this.
I suppose that for release v1.0 we can clear the filter text as a simple alternative and then we can think of a better implementation. I will enter a new post 1.0 enhancement requirement then.

**Comment by kinow** [comment]
New version deployed, hopefully http://162.243.246.75:8080/job/issue-71 now provides the correct behaviour @imoutsatsos

**Comment by kinow** [comment]
Seems to be working now in 1.0. Please feel free to re-open an issue in https://issues.jenkins-ci.org/ with component name active-choices-plugin in case the issue persists. Thanks!
