### ISSUE TITLE
Value changes of Dynamic Reference are cascaded erratically

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#73]
Sometimes they do and sometimes they don't. I have noticed this with a specific sequence of uno-choice parameters and I have reproduced a test case for you here:
http://162.243.246.75:8080/job/issue-73/

Notice that when you first load a page the entire cascade works as it should
![image](https://cloud.githubusercontent.com/assets/3408226/6031523/27fae68c-abce-11e4-9960-a78d7f4d126c.png)

You can explore other ACTIVITY options which propagate updates to the MESSAGE which correctly propagate updates to  the PLACES_FOR_ACTIVITY (which just references the Dynamic Reference parameter MESSAGE).

![image](https://cloud.githubusercontent.com/assets/3408226/6031559/835e9604-abce-11e4-9ced-330d019c37bd.png)

Now, we change the MONTH and this updates the MESSAGE. However, the PLACES_FOR_ACTIVITY are now not updated correctly (still showing the previous values)
![image](https://cloud.githubusercontent.com/assets/3408226/6031590/c50e8bb8-abce-11e4-894d-40fec7bfc72c.png)

However, if you continue to select an ACTIVITY, updates again work. So it is the MESSAGE change cascaded from the MONTH parameter that does not cascade to PLACES_FOR_ACTIVITY

**Comment by kinow** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-28737
