### ISSUE TITLE
UC Dynamic Reference: Missing Reference Parameter when rendered as D3 Graph

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/uno-choice-plugin#74]
Started experimenting with the idea that an uno-choice parameter can be rendered as a fully dynamic D3 graph. 

Initial results **look encouraging!**.
See: http://162.243.246.75:8080/job/TEST_D3_SCATTERPLOT project.

![image](https://cloud.githubusercontent.com/assets/3408226/6254915/14f72ee4-b77a-11e4-968d-ad00753ec811.png)

This is the configuration of the UC Dynamic Reference Parameter displaying the SCATTERPLOT D3 Graph.
![image](https://cloud.githubusercontent.com/assets/3408226/6255239/9474c3a0-b77c-11e4-8d63-2c8193663981.png)

Now I want to  dynamically change the data set that the D3 graph script reads and renders. What a better use than the uno-choice cascading controls!

So here we go! 
Instead of hard coding the data set I created it dynamically by passing a reference to the SPECIES parameter.

![image](https://cloud.githubusercontent.com/assets/3408226/6255008/de0c6a10-b77a-11e4-9641-78d631e7d8a7.png)

Trying to display this fails now.
![image](https://cloud.githubusercontent.com/assets/3408226/6255037/11fe1c38-b77b-11e4-88e0-14265f124329.png)

Reviewing the Jenkins log we see the following error.
![image](https://cloud.githubusercontent.com/assets/3408226/6255061/408ddb60-b77b-11e4-95e9-829cf8ef0bf6.png)

This is peculiar and unexpected. In fact, if I simply change the return value of the SCATTERPLOT parameter to type of 'Input Text Box' and I review its contents, it all seems to be working fine!

It only fails when we do this admittedly complicated HTML rendering of the d3 script.

*If this get's resolved, we have a working example of a dynamic graphical Jenkins application* as I suggested in my BioUno Developers [posting](https://groups.google.com/forum/#!topic/biouno-developers/uQSANvdkVG4) this morning.

**Comment by kinow** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-28738
