### ISSUE TITLE
Please provide a way to hide fields on dynamic references

### ISSUE THREAD

**Issue by pdirksen** [biouno/uno-choice-plugin#78]
As the title says it would be a nice-to-have feature not only to disable fields and their labels but to hide them completely on a dynamic reference.

Thanks

**Comment by imoutsatsos** [comment]
Can you please provide a use case for this request?  As a dynamic reference was originally envisioned for providing user feedback for selecting other parameters I can't quite see the need for hiding it, but perhaps you have come up with a new idea on how to use a dynamic reference parameter.  Thanks!

**Comment by kinow** [comment]
Closing as version 1.0 has been released to Jenkins update centre. Please feel free to re-open an issue in https://issues.jenkins-ci.org/ with component name active-choices-plugin in case the issue persists. Thanks!
