### ISSUE TITLE
no jenkinsProject parameter on Cascade dynamic choice parameter

### ISSUE THREAD

**Issue by qjafcunuas** [biouno/uno-choice-plugin#79]
Hi,

i've tried to get the script.binding.jenkinsProject variable on the groovy script of a Cascade dynamic choice parameter, but it doesn't exit.

uno-choice 0.24

tia

**Comment by kinow** [comment]
Hi @qjafcunuas, we have temporarily enabled issues here while we migrate them to Jenkins JIRA. Could you report your issue there, please? https://issues.jenkins-ci.org, component = active-choices-plugins

Also, the latest version is the 1.0, released to via the Jenkins update center now.
