### ISSUE TITLE
Willy Aguirre: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by marti1125** [biouno/uno-choice-plugin#80]
I have a little experience with jenkins and also I am working as a java developer
I hope to help you!!
https://github.com/marti1125<p><br><blockquote>This issue was created by @marti1125 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by kinow** [comment]
Hi @marti1125 

Happy that you are joining us.

What would you like to work on? Look for something that gets you really excited, that you have fun. In Active Choices Plug-in, any other of our [plugins](http://biouno.org/jenkins-plugins.html) or [projects](http://biouno.org/projects.html).

If you find anything interesting, you can already start hacking and send your questions, issues or pull requests :-)

Or if you need help setting up environment or learning something, you can drop a message in our [mailing lists](http://biouno.org/contact.html).

All the best,
Bruno

**Comment by marti1125** [comment]
I would like to contribute in this project https://github.com/biouno/pbs-java-api

![project](https://cloud.githubusercontent.com/assets/223240/9884153/dd9ae1d8-5ba3-11e5-9191-e7a9dd1b3faa.png)

how to I can test it?

Could I suggest to add some instructions for get start develop in the readme.md?
* mvn clean install
* mvn eclipse:eclipse | mvn netbeans:netbeans | mvn idea:idea

**Comment by kinow** [comment]
Hi @marti1125 

>I would like to contribute in this project https://github.com/biouno/pbs-java-api

Excellent choice! It is in my TODO Lis for the next development cycle, so I think I can either test and review your changes, or work with you fixing/implementing something.

>how to I can test it?

You will have to have a working PBS server. You can use Vagrant or Docker for that, as it is usually easier than getting a real PBS server.

>Could I suggest to add some instructions for get start develop in the readme.md?

Go for it. Documentation and tests are always welcome. If you change anything, try to avoid formatting code or documents, as that makes hard to review your changes.

Send one issue or one pull request for each task (e.g. one issue/pr to update the documentation, not one to update documentation, include a few features, and fix something that is broken).

I will close this task off as it's not really related to uno-choice plug-in. But feel free to open issues in the pbs-java-api repository, send pull request and, of course, use the mailing list.

The main advantage of using the mailing list is that other developers and users may benefit of our discussion there, as not everybody is watching this repository, or the pbs-java-api repository.

If you have a question on how to use or install something, you can use the users mailing list. For development related questions (how to do something in Java, how to set up environment, suggestions, bugs, etc) you can use the developers mailing list.

Welcome aboard, and happy hacking :-)
Bruno

**Comment by marti1125** [comment]
cool =D @kinow  I opened a new post https://groups.google.com/forum/#!topic/biouno-developers/JTddcn6Qem8
